### ISSUE TITLE
Dependency install script misses libssl-dev

### ISSUE THREAD

**Issue by crawlem** [fossology/fossology#825]
I've built fossology from source on Ubuntu and noticed the fo-installdeps script missed out the libssl-dev package. The build failed with the below error until I manually installed the package.

`In file included from util.c:26:0:
delagent.h:33:25: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
                         ^
compilation terminated.`

**Comment by mcjaeger** [comment]
which version is that?

**Comment by crawlem** [comment]
Sorry should have added that - I'm using Ubuntu Server 17.04.

**Comment by mcjaeger** [comment]
hm, actually we (maybe @bcornec , @ag4ums , @max-wittig , I ...) are in the process of supporting 16.04 LTS and centos7 and debian 8, I am not sure we are going for 17.04 in the very near. Your contribution or suggestions to the `fo-installdeps` would be very welcome, however,

**Comment by bcornec** [comment]
Once we're done with our work with pb, adding new distributions to support will be very easy and producing more packages for it as well. It will just take more time and space to store them.

**Comment by mcjaeger** [comment]
@ag4ums rumors exists that you run fossology on 17.04 do you have any ideas here?

**Comment by GMishx** [comment]
`libssl-dev` is a dependency under delagent.
https://github.com/fossology/fossology/blob/master/src/delagent/mod_deps#L84

It should be installed during execution of `fo-installdeps`

**Comment by GMishx** [comment]
Tested and working fine on CentOS 7, Fedora 27, Ubuntu 14.04, Ubuntu 16.04, Debain 8 and Debian 9.
