### ISSUE TITLE
ERROR:  relation "nomos_ars" does not exist

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#437]
I just did an install from source of Fossology based upon "trunk, commit: [#8bba20c] " to a "bare/new" Ubuntu VM and while attempting to process the file https://github.com/agronholm/pythonfutures/archive/2.2.0.zip uploaded via Upload->From URL with "Make Public" and "Nomos License Analysis" options selected, the nomos agent job is failing with:
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: "ERROR: nomos.c:89, ERROR:  relation "nomos_ars" does not exist"
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: "LINE 1: select ars_pk from nomos_ars,agent                 where age..."
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: "                           ^"
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: "On: select ars_pk from nomos_ars,agent                 where agent_pk=agent_fk and ars_success=true                   and upload_fk='3' and agent_fk='2'"
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: agent failed with error code 166
2015-05-20 15:18:55 nomos [0] :: JOB[9].nomos[2932.localhost]: agent failed, code: 166

I "suspect" that this relation is missing from the seed sql database ;)

The system is Ubuntu 12.04 LTS with Postgresql 9.1

**Comment by bobgob** [comment]
Yikes!  It looks like this bug was introduced in ee5587e on Aug 8, 2014.  How could this not have been discovered until now?  The problem is caused by querying the  nomos_ars table  before the call to fo_WriteARS().   fo_WriteARS() creates nomos_ars if it does not exist.  

```
    /* if it is duplicate request (same upload_pk, sameagent_fk), then do not repeat */
    snprintf(sqlbuf, sizeof(sqlbuf),
        "select ars_pk from nomos_ars,agent \
                where agent_pk=agent_fk and ars_success=true \
                  and upload_fk='%d' and agent_fk='%d'",
        upload_pk, gl.agentPk);
    result = PQexec(gl.pgConn, sqlbuf);
    if (fo_checkPQresult(gl.pgConn, result, sqlbuf, __FILE__, __LINE__))
      Bail(-__LINE__);
    if (PQntuples(result) != 0)
    {
      LOG_NOTICE("Ignoring requested nomos analysis of upload %d - Results are already in database.", upload_pk);
      PQclear(result);
      continue;
    }
    PQclear(result);
    /* Record analysis start in nomos_ars, the nomos audit trail. */
    ars_pk = fo_WriteARS(gl.pgConn, ars_pk, upload_pk, gl.agentPk, AgentARSName, 0, 0);
```

**Comment by yaobinshi** [comment]
it is a critical defect. 

one question: 
when one upload has been in nomos_ars, why stop to do nomos scan?
from my point, stop only when one file has been scanned by same version of nomos agent  
for nomos, granularity is file, no upload.

**Comment by steffen-weber** [comment]
How about a major change of the database schema? Instead of inheritance, all ars results could be saved in ars_master.
* This would avoid the risk, that any agent 'forgets' to create its ars table.
* Since constraints are not inherited in PostgreSql, each ars table has to take care that the primary key is correctly initialized. A common table would skip this overhead.
* The latest successful agent ids for all scanner can be easily queried at once.

**Comment by bobgob** [comment]
@yaobinshi I think you are mixing up what the ars table does and what nomos does.  The ars table is used to see if a specific agent version has been run successfully on a specific upload.   Nomos  will only select files that have not been scanned by the running nomos version.  The ars table keeps the browser from reporting incomplete results from a nomos scan that failed part way through.  It also, provides a quick check to see if anything needs to be scanned.  A query to nomos_ars to see if nomos version xyz  successfully completed on upload abc is much faster than querying the license_ref table to find any files that still need scanning.

@steffen-weber the reasons the ars tables use inheritance are:
* The latest successful agent ids for all scanner can be easily queried at once.  You only have to query the master table.
* Agent results might not be dependent on a single agent version.  Currently, this only applies to bucket results.  The bucket agent has additional dependencies on nomos and the bucketpool that was used.  So bucket_ars inherits from the master and then adds nomosagent_fk and bucketpool_fk.

Of course, buckets could be treated as an outlier and all the other agents could use a single table.  There aren't any current plans for new agents that have dependencies on other agent data.  This would also mean a single query to the master table will not show all the successful agents run on an upload.

**Comment by yaobinshi** [comment]
@bobgob you are correct, that is my bad, thanks.

how about move the duplicate checking code  fo_WriteARS function, do the duplicate after trying to create ars table?
191   /* does ars table exist?  If not, create it.  */
192   if (!fo_CreateARSTable(pgConn, tableName)) return (0);

**Comment by bobgob** [comment]
That sounds like a good idea.  Just be aware that fo_WriteARS() doesn't only write new records, it is also used to update ars records.  So you only want to check for a duplicate ars record if ars_pk == 0.  And we will also need a new return code for the duplicate.

**Comment by fogninid** [comment]
02adea0 broke bulk scanning. I have added a (failing) testcase to monk Functional tests.

**Comment by bobgob** [comment]
02adea0 is very broken.  See my comment above about fo_WriteARS() also being used to update records.  You can't return just because a record exists, you have to check ars_pk to see if it is an update.  

The duplicate request sql and subsequent logic looks wrong to me (line 197, libfossagent.c):
```
snprintf(sql, sizeof(sql),
      "select ars_pk, ars_success from %s,agent \
      where agent_pk=agent_fk and upload_fk='%d' and agent_fk='%d'",
      tableName, upload_pk, agent_pk);
```
*  I don't see any reason to include a join with the agent table.  The result (ars_success) and the criteria (agent_fk, upload_fk) are all in the ars table.
*  The query won't work anyway since you can get multiple rows returned and you are only checking the first one.  For example, there might have been failures before a success.

So to fix this, remove the duplicate checking code you added and add the following duplicate query after line 220 ```if (!ars_pk)``` :
```
snprintf(sql, sizeof(sql),
      "select ars_pk, ars_success from %s \
      where upload_fk='%d' and agent_fk='%d' and ars_success=true",
     upload_pk, agent_pk);
```
If any records are returned then you know you have a duplicate and can return -1.
And in nomos.c you need to check the return value of fo_WriteARS() (line 83) to know if you can continue.

**Comment by yaobinshi** [comment]
bob,
1. for bucket agent, days ago, bucket_ars table definition is  removed from ./src/www/ui/core-schema.dat, do you know why?

and
in bucket.c , bucket does not use fo_WriteARSlike like other agents do.
in AgentHasResults of agent-bucket.php, has a different logic with other agents.
that is why fails when upload something with bucket job.
for me, add bucket_ars table definition back to the schema file will spend less jobs.

2. for duplicate check in fo_WriteARS
thanks for your comments, agree, move the duplicate check code to if (!ars_pk) .

snprintf(sql, sizeof(sql),
      "select ars_pk, ars_success from %s \
      where upload_fk='%d' and agent_fk='%d' and ars_success=true",
     upload_pk, agent_pk);

except users run nomos through fossjobs mutiple times, duplicate check will never be used.
if is impossible to reschedule nomos again from UI when it is successful(no show in the box). 

in the sql above, use 'ars_success=true' is incorrect, ars_pk is 0, that mean, the start(1st one) fo_WriteARS is called, in case  the agent was failed, we should just return the ars_pk, do not insert and update anything, the end(2nd one)fo_WriteARS, will the do the update job.

also I do not understand why you say one upload with specific version agent possibly have multiple records.

**Comment by bobgob** [comment]
*  I  wrote @fogninid about why he removed bucket_ars from core-schema.dat.  It looks like a mistake to me.  Thanks for bringing it up.

* buckets doesn't update the bucket_ars table like the other agents because all the other agent _ars tables inherit from master_ars and make no changes.  bucket_ars inherits but adds new fields since bucket results have dependencies the other agents don't (on nomos and pkgagent and should have the other license scanners added).
* If a agent job has been successful, then that agent should be missing from the agent pull down in Jobs > Schedule agents if there is a successful ars record.  The ars records are keyed to the agent revision and, in the case of buckets, all the dependency agents and their revisions.  The idea being that if you scanned it once successfully with agent X revision Y, then there is no reason to rerun it.  If the agent is updated (new version), then it will show in the select list again.  This is why monk bumps the agent rev when someone updates the license_ref table.
* One upload with a specific agent version can have multiple ars records.  For example, let's say a scan was started and the machine crashed.  That ars record will have ars_success == false.  Then if you rerun it again you can get an ars_success == true.  So you end up with multiple records.  This happens in development all the time when we are working agent code.  We run it once and it fails, so we make a code change and run it again (and again).

**Comment by yaobinshi** [comment]
bob, will ping you on this Friday china time.

**Comment by pguttmann** [comment]
As of commit 6dcf252309674ea4c81451e0eb9bbb850006844e a nomos license scan can be  successfully initiated from the Upload => from file menu option.

**Comment by yaobinshi** [comment]
this issue has been fixed in the schema file, thanks.
